### ISSUE TITLE
How to use your controller

### ISSUE THREAD

**Issue by celluj34** [nebrius/aquarium-control#1]
Hi Bryan!

I found your post at https://theoreticalideations.com/2013/05/10/node-js-raspberry-pi-aquarium-awesome/ and I think this is an awesome project! I just recently purchased my own 75 gallon tank, and I was looking to see if there were any  projects out there to control some LEDs instead of paying outrageous amounts of money for a lighting "solution". Lo and behold I found yours!

My question is thus: if I wanted to use your project to light my tank, what would I need to do? Is there a list of things I need to purchase? Or, for example, what kind/how many lights can I use?

I already have a Pi, but I have not tinkered with it yet. Please let me know if you have any questions. Thanks!

**Comment by nebrius** [comment]
Funny you mention this now. I'm in the middle of rewriting the software as we speak. The internet endpoint I used for determining sunrise/sunset times went offline, and taking it out proved problematic. Hopefully I'll be done later this week.

The software itself should be easy to reuse, and I plan to publish to NPM with this rewrite. The trick is interfacing with the lights themselves. This part is totally DIY.

You'll need something to "translate" between the lights and the raspberry pi's voltage. Something like this: http://www.amazon.com/SainSmart-Channel-Arduino-Isolation-Voltage/dp/B008BGLM02/ref=sr_1_cc_1?s=aps&ie=UTF8&qid=1440373010&sr=1-1-catcorr&keywords=sainsmart+3.3v+solid+state+relay

After that, interfacing with your lights is something you'll have to figure out on your own, unfortunately. You'll have to take the cable going to the lights on your aquarium and cut it. Inside, there will most likely be three wires. If this is the case, one will be power or ground, and the other two the control signals (one for day, one for night). You'll need to figure out which is which using a multimeter.

I should mention a disclaimer: it is entirely possible that you will damage your lights in the process of hacking, so take care. Also take care when working with live electricity, I don't want you to accidentally get hurt :)

**Comment by marconealberto** [comment]
Hi, this module looks great! any updates on your rewriting?

**Comment by nebrius** [comment]
> Hi, this module looks great! any updates on your rewriting?

Yeah, the rewrite was completed not long after I posted that :)
